LICENSE = '''\
Probabilistic Genotyping ToolKit  Copyright (C) 2018  Graham Northup et. al.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
'''

UNVERIFIED = '''\
The results and conclusions generated by this program HAVE NOT BEEN VALIDATED
OR TESTED by a relevant authority or expert. Use these data AT YOUR OWN RISK.
'''

COMPLIANCE = '''\
!!! WARNING !!!
You have specified options which affect the compliance of this program versus a
reference implementation. Do NOT assume these data will be relevant to that
implementation; use them AT YOUR OWN RISK. These options are detailed below:'''

UNDEFINED_BEHAVIOR = '''\
\x1b[31;1;6m!!! WARNING !!!\x1b[m
The program has detected an instability which may cause undefined behavior. DO
NOT trust the integrity of data output, even if output is generated! The
problems are detailed below:'''
